### PR TITLE
Countdown timer made responsive and expire issue resolved

### PR DESCRIPTION
**Pull request by Abhinav-Singh-Bisht**
Countdown timer was not responsive 
Capture
>
Capture2

Capture3
Capture4

### CODE REVIEW

**Comment by Abhinav-Singh-Bisht** [comment]
i removed the text shadow style as it was creating problem in smaller screens

**Comment by Abhinav-Singh-Bisht** [comment]
Thanks for merging my pr but sir one problem i saw that one of my commit
was not merged i dont know  why but it is important for the timer style so
should i make a new pr or can u please make the desired changes

the code that needs to be added after 41 line is
  font-size: 70px;
  color: #f74700;
  background-color: #f4f0e1;
  border-radius: 20px;
  /* text-shadow: 2px 2px rgb(181 58 37); */
  box-shadow: 1px 1px 1px 1px rgb(181 58 37);

**Comment by rakshit234** [comment]
Make another PR.

**Comment by Abhinav-Singh-Bisht** [comment]
Done sir

**Pull request merged**
